### ISSUE TITLE
"superclass mismatch for class Attribute"

### ISSUE THREAD

**Issue by karrkode** [karrkode/follow_up#15]
I'm running into an error when my Travis CI runs, overlapping definitions of the Attribute class are preventing it from running smoothly. Click [here](https://stackoverflow.com/questions/46472997/typeerror-superclass-mismatch-for-class-task) to read a stackoverflow description of the error.

The error appears like this: 
![image](https://user-images.githubusercontent.com/2112037/31804198-5504a8ec-b51d-11e7-9536-bab2baa1968b.png). 

The main issue is that I don't get where the Attribute class exists and thus am unable to find where the competing definitions occur. The relevant files (I assume), are the .travis.yml file and the config/environment.rb file. 

If anybody has any insight, I'd gladly listen. @jbranchaud, may come in tomorrow if I can't resolve this.

**Comment by karrkode** [comment]
This was resolved by updating the TravisCI file to use Ruby 2.2.5. The 'Before Install: Bundle Install' was also a redundancy that was removed. The install was also reduced to only have 'bundle install'. See travis branch for more information.

**Comment by karrkode** [comment]
Much thanks to @jbranchaud and Dylan at @hashrocket for helping me out!

**Comment by jbranchaud** [comment]
@dillonhafer ^^ 💕
